### ISSUE TITLE
Sensors for Home Assistant

### ISSUE THREAD

**Issue by JensAtGitHub** [kellerza/pysma#13]
I have HA running with connection tomy sma sunny boy 3.6 -40.

Nevertheless I do only get the first 4 Sensors from the list integrated:
```
SENSORS = [
    Sensor('current_consumption', '6100_00543100', 'W'),
    Sensor('current_power', '6100_40263F00', 'W'),
    Sensor('total_consumption', '6400_00543A00', 'kWh', 1000),
    Sensor('total_yield', '6400_00260100', 'kWh', 1000),
    Sensor('grid_voltage', '6100_00464800', 'V'),
    Sensor('pv_power', '6100_0046C200', 'W'),
    Sensor('daily_yield', '6400_00262200', 'Wh'),
    Sensor('power_supplied', '6100_00464800', 'W'),
    Sensor('power_absorbed', '6100_00464800', 'W'),
    Sensor('status', '6180_08214800', '', None, '."1"[].val[0].tag'),
]
```
adding the other sensors results in a faulty configuration.yaml. What helps is to integrate custom sensors . These sensor defintions work for me:

```
 sensors:
      current_consumption:
      current_power:
      total_consumption:
      total_yield:
      sma_grid_voltage:
      sma_daily_yield:
    custom:
        sma_grid_voltage:
            key: "6100_00464800"
            unit: V
        sma_daily_yield:
            key: "6400_00262200"
            unit: Wh

```
- Is there a copy paste mistake in pysma since in above definition the sensor key` 6100_00464800` is used for multiple sensors?
- Does anybody have a clue for the sensor keys for consumption / yield - today / yesterday. 
Thanks & regards.
