### ISSUE TITLE
Could not start session, Session ID expected 

### ISSUE THREAD

**Issue by dimitriy-k** [kellerza/pysma#21]
Sunny Boy 2.5
Home Assistant 0.94.3

```
Could not start session, Session ID expected [result.sid], got {'result': {'sid': None}}
9:47 PM components/sma/sensor.py (ERROR) - message first occured at 9:47 PM and shows up 4 times
```

configuration:
```
- platform: sma
  host: 192.xxx.xxx.xxx
  password: !secret password
  verify_ssl: false
  group: user
  sensors:
    daily_yield:
    status:
```
