### ISSUE TITLE
Tigo optimizers still need the custom sensor

### ISSUE THREAD

**Issue by popoviciri** [kellerza/pysma#62]
I use Tigo optimizers logged by my Sunny Tripower via a Tigo Access Point (TAP). The following custom sensors are logging Power and Temperature of each optimizer (only first two shown as example):
```
- platform: sma
  custom:
    power_tigo_1:
      key: '6100_40652A00'
      unit: W
      factor: 1
      path: '"1"[0].val'
    power_tigo_2:
      key: '6100_40652A00'
      unit: W
      factor: 1
      path: '"1"[1].val'
    temperature_tigo_1:
      key: '6100_40652B00'
      unit: °C
      factor: 10
      path: '"1"[0].val'
    temperature_tigo_2:
      key: '6100_40652B00'
      unit: °C
      factor: 10
      path: '"1"[1].val'
```
To add this in the main integration may be complicated since requires additional inputs regarding the number of panels monitored, if any.
Please consider keeping the yaml custom sensor alongside the GUI integration, unless this is a hard requirement from the Homeassistant folks.
Will keep using a custom integration for now. Thanks for your work!
Cheers!
