### ISSUE TITLE
Fetching data from 2 (or more) devices with overlapping sensor-ids?

### ISSUE THREAD

**Issue by cpohli** [kellerza/pysma#65]
Hi there,
first of all a big thank you for your efforts on this, it makes my day a lot more informative (multiple times :-)

Ok, so here is what i actually have (preventing me from update HA to post 21.4)
- SMA Tripower (for the solar panels)
- SMA Sunny Island (for the battery)
I successfully configured both devices via YAML (getting some "sensor-id already exists, will be ignored") with some standard (pysma)sensors and some (about 7) custom sensors.

This i do have to do, because for instance the battery specific sensors are only given by the Sunny Insland, some others only given by the TriPower, some are given by both (identical readouts, but different ids or even identical ids).

I do need sensors from both devices for quite a lot of template sensors to get the bigger picture of the whole installation.

If i am right, after updating post 21.5.x i can only configure ONE device via integrations and cannot use the custom sensors anymore, right?

So i am basically stuck with 21.4.x (i am relying on my personal HA solar dashboard and some calculations that are done there)?

I would very much like to contribute to the pysma library to get the custom sensor data included (how would i do that (new to github stuff, sorry)) and foremost to work out an integration of more than one device. Is that even planned/thought of?)

Thank you very much.

PS; My YAML integration at the moment looks like this (excerpt)
```yaml
################################################################################
# SMA Solar - Tripower
################################################################################
- platform: sma
    host: 192.168.0.xxx
    ssl: true
    verify_ssl: false
    password: xxx
    sensors:
#      - current_consumption
#      - total_consumption
      - pv_power
      - daily_yield
      - total_yield
      - grid_power_supplied
      - grid_power_absorbed
#      - grid_power
#      - grid_total_yield

################################################################################
# SMA Akku - Sunny Island 4.4
################################################################################

  - platform: sma
    host: 192.168.0.yyy
    password: yyy
    sensors:
#      - total_yield

    custom:
      sma_si_batt:
        key: '6100_00295A00'
        unit: '%'
        factor: 1
        path: '"7"[0].val'
      sma_si_lad:
        key: '6100_00496900'
        unit: W
        factor: 1
        path: '"7"[0].val'
      sma_si_entlad:
        key: '6100_00496A00'
        unit: W
        factor: 1
        path: '"7"[0].val'
      sma_batt_temp:
        key: '6100_40495B00'
        unit: °C
        factor: 1
        path: '"7"[0].val'`
```
