### ISSUE TITLE
Allow keys with more than 13 characters

### ISSUE THREAD

**Issue by MimbaMonkeyHouse** [kellerza/pysma#7]
Some keys in Webconnect use more than 13 characters. This is the case, for instance, for inverters with 2 separate arrays/MPTT. Here is what I found on my Sunnyboy 5.0:
```
  custom:
    sma_status: 
      key: "6180_08214800"
    sma_power_a:
      key: "6380_40251E00_0"
      unit: W
    sma_power_b:
      key: "6380_40251E00_1"
      unit: W
    sma_voltage_a:
      key: "6380_40451F00_0"
      unit: V
    sma_voltage_b:
      key: "6380_40451F00_1"
      unit: V
    sma_current_a:
      key: "6380_40452100_0"
      unit: A
    sma_current_b:
      key: "6380_40452100_1"
      unit: A
```
It can be interesting to be able to monitor several arrays separately rather than the entire output of an inverter. This would for example allow users to better determine the effect of shading, orientation and inclination on PV output.

Can the pysma code be corrected easily to account for these sensor keys with 15 characters?
